default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: recruiting_dashboard_test

development:
  <<: *default
  database: recruiting_dashboard_development